# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

ENV_MODULE_NAME = 'MODULE_NAME'
ENV_FUNCTION_NAME = 'FUNCTION_NAME'

MODULE_NAME_DEFAULT = 'func'
FUNCTION_NAME_DEFAULT = 'main'
SEARCH_PATH_DEFAULT = '.'
