api = "0.6"

[buildpack]
  id           = "kn-fn/java-function"
  name         = "Java Function Buildpack"
  version      = "{{.version}}"
  sbom-formats = ["application/vnd.syft+json"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml", "VERSION"]
  pre-package = "./build.sh"

  [[metadata.dependencies]]
    id      = "invoker"
    name    = "Java Invoker"
    version = "0.0.2"
    uri     = "https://storage.googleapis.com/cnr-functions-release/kn-fn/java/java-function-invoker-0.0.2.jar"
    sha256  = "db3228e5de0dd28547a653c52833eba6b92b6b0c3c8393d32466a6f9f267dbdd"
    stacks  = [ "io.buildpacks.stacks.bionic" ]
