api = "0.6"

[buildpack]
id       = "kn-fn/java-function"
name     = "Java Function Buildpack"
version  = "0.0.1"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.configurations]]
name        = "KN_FN"
description = "whether this is a function"
build       = true

[[metadata.dependencies]]
id      = "invoker"
name    = "Java Invoker"
version = "0.0.1"
uri     = "https://storage.googleapis.com/cnr-functions-release/deleteme/java/java-function-invoker-0.0.1.jar"
sha256  = "644733fcd08759c9332a4f589f799664c524d9fad6bc9d79fc0e19f856e53bbb"
stacks  = [ "io.buildpacks.stacks.bionic" ]
