api = "0.6"

[buildpack]
  id           = "kn-fn/java-function"
  name         = "Java Function Buildpack"
  version      = "{{.version}}"
  sbom-formats = ["application/vnd.syft+json"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml", "VERSION"]
  pre-package = "./build.sh"

  [[metadata.configurations]]
    build = true
    default = "functions.Handler"
    description = "The function to run. It must be in the format of <package>.<class>, if it is in the default package then just <class>"
    name = "BP_FUNCTION"
  
  [[metadata.configurations]]
    build = true
    default = ""
    description = "The default function name. In the event there are multiple functions. Specifying the name of the function will make it accessible through the root path '/'"
    name = "BP_DEFAULT_FUNCTION"

  [[metadata.dependencies]]
    id      = "invoker"
    name    = "Java Invoker"
    version = "0.0.2"
    uri     = "https://github.com/vmware-tanzu/function-buildpacks-for-knative/releases/download/java-invoker%2Fv0.0.2/java-function-invoker-0.0.2.jar"
    sha256  = "4606a9cde3dbf5ceb8152d45a8c8069adeecb86fed8c748645e904eb42b8f594"
    stacks  = [ "io.buildpacks.stacks.bionic" ]
