# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

#@data/values-schema
---
buildpack:
  #@schema/type any=True
  version: "{{ .version }}"

invoker:
  version: 0.0.0
  url: ""
  sha: ""
