# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: awscreds
  namespace: #@ data.values.namespace
data:
  aws_access_key_id: #@ base64.encode(data.values.triggermesh.accesskey)
  aws_secret_access_key: #@ base64.encode(data.values.triggermesh.secretkey)
