# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

#@ load("@ytt:data", "data")
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger
  namespace: #@ data.values.namespace
spec:
  broker: broker
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: consumer
     namespace: #@ data.values.namespace
    uri: /func
