# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: my-aws-creds
  namespace: #@ data.values.namespace
data:
  aws-access-key: #@ base64.encode(data.values.app.accesskey)
  aws-secret-key: #@ base64.encode(data.values.app.secretkey)
  aws-session-key: #@ base64.encode(data.values.app.sessionkey)
