# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: 'SRP Helper Submit'
description: 'Helper action to submit data for VMware SRP CLI'
runs:
  using: "composite"
  steps:
    - id: submit
      run: ${{ github.action_path }}/submit.sh
      shell: bash
