# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

apiVersion: v1
kind: Secret
metadata:
  name: my-aws-creds
  namespace: cnr-demo
type: Opaque
stringData:
  aws-access-key-id: "ACCESS_KEY_ID"
  aws-secret-access-key: "SECRET_ACCESS_KEY"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: approver
  namespace: cnr-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: gcr.io/daisy-284300/dolfo/approver
          imagePullPolicy: Always
          env:
            - name: FLASK_ENV
              value: development
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-creds
                  key: aws-access-key-id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-creds
                  key: aws-secret-access-key
---
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source
metadata:
  name: my-bucket
  namespace: cnr-demo
spec:
  # This should point to your aws s3 bucket IE: arn:aws:s3:us-west-2:925906438773:demobkt-triggermesh
  # The default ARN from AWS needs the region and your account ID added to it as above:
  # https://docs.triggermesh.io/sources/awss3/#amazon-resource-name-arn
  arn: "arn:aws:s3:us-west-1:612314536519:dolfo-parul-func"
  credentials:
    accessKeyID:
      valueFromSecret:
        name: my-aws-creds
        key: aws-access-key-id
    secretAccessKey:
      valueFromSecret:
        name: my-aws-creds
        key: aws-secret-access-key

  eventTypes:
  - s3:ObjectRemoved:*
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
      namespace: cnr-demo

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger
  namespace: cnr-demo
spec:
  broker: default
  filter:
    attributes:
      type: com.amazon.s3.objectremoved
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: approver
      namespace: cnr-demo

