# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: Check Copyright and License
on:
  pull_request:

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
      - run: go version
      - name: Check Copyright and License
        run: make check-copyright
