name: Check Copyright and License
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
      - run: go version
      - name: Check Copyright and License
        run: make check-copyright
