# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: CodeCov
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'buildpacks/**'
    - 'invokers/**'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  code-cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - run: go version
    - name: Run Buildpack Tests
      run: make buildpacks.tests
    - name: Run Python Invoker Tests
      id: python-invoker-tests
      run: make invokers.python.tests
    - name: Run Java Invoker Tests
      run: make invokers.java.tests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
       token: ${{ secrets.CODECOV_TOKEN}}
