# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: Integration Tests
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'buildpacks/**'
    - 'invokers/**'
    - 'builder/**'
    - 'tests/integration/**'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - run: go version
    - name: Run Integration Tests
      run: make integration-tests
