name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - run: go version

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
#     - name: configure
#       run: ./configure

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Install dependencies
      run: make
    - name: Make Builder
      run: make builder

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run Buildpack Tests
      run: make tests
    - name: Run Smoke Tests
      run: make test-images smoke-test
      
#     - name: Build and Publish
#       run: make publish
