name: Test Builder
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'builder/**'
    - 'tests/**'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.8'
    - run: go version
    - name: Create Builder
      run: make builder
    - name: Run Smoke Tests
      run: make smoke-tests
