# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: Test Buildpacks
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'buildpacks/**'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  buildpack-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - run: go version
    - name: Run Buildpack Tests
      run: make buildpacks.tests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
       token: ${{ secrets.CODECOV_TOKEN}}
       files: ./buildpacks/common/coverage.out, ./buildpacks/java/coverage.out, ./buildpacks/python/coverage.out 
       flags: test-buildpacks
