# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: Test Templates
on:
  workflow_dispatch: {}
  push:
    paths:
    - 'builder/**'
    - 'templates/**'
    - 'tests/**'
  schedule:
    - cron: '0 6 * * 1'

env:
  REGISTRY: ghcr.io
  CONTAINER_PATH: ${{ github.repository }}
  DEPENDENCY_BASE_URL: https://github.com/${{ github.repository }}

jobs:
  template-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - run: go version
    - name: Run Template Tests
      run: make base_url=${{ env.DEPENDENCY_BASE_URL }} registry.location=other REGISTRY=${{ env.REGISTRY }}/${{ env.CONTAINER_PATH }} template-tests
