# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

name: Vmware SRP Report

on:
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - Create Buildpack Release
      - Create Invoker Release
    types:
      - completed
jobs:
  srp:
    name: VMware SRP Report
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      if: ${{ github.event_name == 'workflow_dispatch'}}
    - name: Check SRP Creds
      uses: ./.github/actions/srp-helper/check-srp-creds
      with:
        client-id: ${{ secrets.SRP_CLIENT_ID }}
        client-secret: ${{ secrets.SRP_CLIENT_SECRET }}
    - name: Install SRP
      uses: ./.github/actions/srp-helper/install
    - name: Initialize SRP
      uses: ./.github/actions/srp-helper/init
      with:
        client-id: ${{ secrets.SRP_CLIENT_ID }}
        client-secret: ${{ secrets.SRP_CLIENT_SECRET }}
    - name: Collect SRP
      uses: ./.github/actions/srp-helper/collect
      with:
        git-repos: .
    - name: Submit SRP
      uses: ./.github/actions/srp-helper/submit
