# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

apiVersion: v1
kind: Secret
metadata:
  name: my-aws-creds
  namespace: cnr-demo
type: Opaque
stringData:
  aws-access-key-id: "AWS ACCESS KEY ID" # CHANGE ME
  aws-secret-access-key: "AWS SECRET ACCESS KEY" # CHANGE ME
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: encrypter
  namespace: cnr-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: gcr.io/daisy-284300/dolfo/encrypter
          imagePullPolicy: Always
          env:
            - name: FLASK_ENV
              value: development
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-creds
                  key: aws-access-key-id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-aws-creds
                  key: aws-secret-access-key
            - name: AWS_S3_BUCKET_NAME
              value: "secrets-encrypted"
---
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSSQSSource
metadata:
  name: sqs-invoice-source
  namespace: cnr-demo
spec:
  #arn: "arn:aws:sqs:us-west-1:612314536519:invoice-queue"
  arn: "arn:aws:sqs:[REGION]:[ACCOUNT_ID]:[SQS INSTANCE NAME]" # CHANGE ME
  credentials:
    accessKeyID:
      valueFromSecret:
        name: my-aws-creds
        key: aws-access-key-id
    secretAccessKey:
      valueFromSecret:
        name: my-aws-creds
        key: aws-secret-access-key

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
      namespace: cnr-demo

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger
  namespace: cnr-demo
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: encrypter
      namespace: cnr-demo

